---
components_bucket_name: "eth-quest-components"

region: "eu-west-2"

component: "nxt-node"

common_state_key: "environment/deployment-state/common/default.tfstate"
network_state_key: "environment/deployment-state/network/%{hiera('deployment_identifier')}.tfstate"
cluster_state_key: "environment/deployment-state/cluster/%{hiera('deployment_identifier')}.tfstate"

image_version_key: "nxt-node/metadata/version"

secrets_bucket_name: "eth-quest-nxt-node-secrets-%{hiera('deployment_identifier')}"

blockchain_archive_url: "https://ardor.tools/nxt.h2.db.1438599.zip"
blockchain_archive_bucket_name: "eth-quest-nxt-node-data-%{hiera('deployment_identifier')}"
blockchain_archive_key: "nxt-node/blockchain-archive/nxt-db.zip"
blockchain_archive_chunk_size_bytes: 10485760

image_repository_state_key: "nxt-node/deployment-state/image-repository/default.tfstate"
secrets_bucket_state_key: "nxt-node/deployment-state/secrets-bucket/%{hiera('deployment_identifier')}.tfstate"
blockchain_archive_lambda_state_key: "nxt-node/deployment-state/blockchain-archive-lambda/%{hiera('deployment_identifier')}.tfstate"
service_state_key: "nxt-node/deployment-state/service/%{hiera('deployment_identifier')}.tfstate"
