---
vars:
  region: "%{hiera('region')}"

  image_name: 'aws-nxt'

backend_config:
  bucket: "%{hiera('components_bucket_name')}"
  key: "%{hiera('nxt_image_repository_state_key')}"
  region: "%{hiera('region')}"
