---
vars:
  region: "%{hiera('region')}"

  bucket_name: "%{hiera('secrets_bucket_name')}"

backend_config:
  bucket: "%{hiera('components_bucket_name')}"
  key: "%{hiera('secrets_bucket_state_key')}"
  region: "%{hiera('region')}"