---
vars:
  region: "%{hiera('region')}"

  image_name: 'aws-ardor'

backend_config:
  bucket: "%{hiera('ardor_image_repository_state_bucket_name')}"
  key: "%{hiera('ardor_image_repository_state_key')}"
  region: "%{hiera('region')}"
  encrypt: "true"
