---
vars:
  region: "%{hiera('region')}"

  image_name: 'aws-cert-manager'

backend_config:
  bucket: "%{hiera('cert_manager_image_repository_state_bucket_name')}"
  key: "%{hiera('cert_manager_image_repository_state_key')}"
  region: "%{hiera('region')}"
  encrypt: "true"
